### PR TITLE
Make NavigationService more extendable

### PR DESCRIPTION
**Pull request by PascalAOMS**
Necessary to easily extend the method for other item types of links.

**Example:**
We need to localize URLs which have the item type "LocalizedCMSLinkComponent".
As the service method explicitly checks for "CMSLinkComponent" it's not possible to use any other types.

### CODE REVIEW

**Comment by PascalAOMS** [comment]
If you have questions regarding the usecase, please let me know. :)

**Comment by alexHerrmi** [comment]
Push

**Comment by PascalAOMS** [comment]
Can we do something here?

**Comment by giancorderoortiz** [comment]
Closing due to many months of inactivity.
If still relevant, please update PR with latest develop branch, and re-open with meaningful comments so that it can be evaluated by development team.

**Comment by Adam-Michalski** [comment]
Hi, Can it be reopened @PascalAOMS

**Pull request closed without merging**
