### PR TITLE
feat: Replace select with ng-select for update profile and registration (#3490)

### LINKED ISSUE #3490: Not-CSS: Samsung s10+ Firefox: Missing title in Personal Details drop down menu
**Environment Details**
Spartacus: Release 1.0
Browser: Firefox
Device: samsung s10+
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/electronics-spa/de/USD/

**Steps to Reproduce**
Go to MyAccount -> Personal Details
Click on the drop down menu for title.

**Actual Result**
The arrow for the drop down menu is too much on the right.
abcc3f83-e38a-4a69-9c38-3c322bd2daf1

Then when the menu is open, the first radio button doesn't have a title name to it.
9adebfd9-cdd5-4f4f-8c4c-0555559ca96f

### PR DESCRIPTION
**Pull request by dydome**
close #3490

### CODE REVIEW

**Comment by developpeurweb** [comment]
On my end, I can't retest on a real Android device until deployed to a server, the same goes for SR Android (Talkback).
So, I guess we'll have to merge first. **Please make sure an angular dev approves the code before merging.**

**Review by FollowTheFlo — CHANGES_REQUESTED** [review]
I found a bug while testing. steps:
- 1 -> login, go personal details, change title (Mr,Miss,Ms...) save, logout.
- 2 -> login again, a blank line is added to selection 
- Do steps 1-2 again, new blank line gets concatenated
https://sap-my.sharepoint.com/:i:/p/florent_letendre01/EUiHofKbItlBlubQHOPdy4cBGm7r0vVPhe_9Bp4gwMJL3Q?e=iIk0W7
image

**Review by FollowTheFlo — APPROVED** [review]
code looks fine,  i fixed all the e2e that needed changes to have green checks: replacing select by ng-select and also title names, dr to Dr., mr to Mr.

**Comment by developpeurweb** [comment]
> On my end, I can't retest on a real Android device until deployed to a server, the same goes for SR Android (Talkback). So, I guess we'll have to merge first. **Please make sure an angular dev approves the code before merging.**

Seems an angular dev has approved the PR. Nothing on my end to test at this point, pls proceed to merge if all good code-wise.

**Pull request merged**
