### PR TITLE
fix: css visibility adjustments to form errors with role alert

### LINKED ISSUE #13676: All form validation error messages should be vocalized as soon as they happen
**Describe the bug**
- Consistently all throughout, none of the form validation error messages are currently being vocalized by any screen reader software.

**Tell us the version of Spartacus**
- Library version: 4.0.0.

**To Reproduce**
1. Open any Screen Reader (VO, NVDA, JAWS).
2. Go to the Sign-In page
3. Introduce invalid email in the form and leave the password field blank.
4. See errors, and hear the absence of vocalization of those same errors.

**Non-thorough list of UIs where this is needed:**
- Login
- Registration
- Coupon field
- Payment details
- My Account > Personal details
- My Account > Password
- My Account > Email Address

**Expected behavior**
- All form validation error messages get vocalized as soon as they happen.
- Since this need the user immediate attention, `aria-live="assertive" aria-atomic="true"`
- E.g.     `<cx-form-errors  aria-live="assertive" aria-atomic="true"></cx-form-errors>`

**Screenshots**

Screen Shot 2021-09-09 at 8 31 02 PM

**Example of potential solution**

Screen Shot 2021-09-09 at 7 59 38 PM

### PR DESCRIPTION
**Pull request by developpeurweb**
Closes GH-13676

### CODE REVIEW

**Comment by Pucek9** [comment]
Styling has been changed for testing (as few changes as possible), but it most probably cannot stay in this form. Current resetting can be too invasive and overwrite styles that perhaps shouldn't be changed (?). Let's provide an alternative solution, even it causes more breaking changes.

**Review by Matejk00 — DISMISSED** [review]

**Comment by developpeurweb** [comment]
It seems there is a bug I didn't catch last time, as soon as the page loads, the alert is vocalized, even without triggering it, this is consistent for all 3 SR.

Screen Shot 2022-03-07 at 1 40 56 PM

**Comment by developpeurweb** [comment]
It now works well with JAWS/NVDA/VO

**Review by Matejk00 — DISMISSED** [review]

**Comment by developpeurweb** [comment]
Still works well with JAWS/NVDA/VO after changes.

**Review by Pucek9 — APPROVED** [review]

**Pull request merged**
