### PR TITLE
fix:  All mandatory form fields must vocalize "required" as soon as they gain focus

### LINKED ISSUE #13678: All mandatory form fields must vocalize "required" as soon as they gain focus
**Describe the bug**
- Consistently all throughout, none of the mandatory form fields are currently being vocalized as "Required" by any screen reader software.

**Tell us the version of Spartacus**
- Library version: 4.0.0

**To Reproduce**

1. Open any Screen Reader (VO, NVDA, JAWS).
2. Go to the Sign-In page
3. Tab to the email address field.
4. Hear the absence of vocalization about this field being required.
5. Tab to the password field, same issue.

**Expected behavior**
- All mandatory form fields must vocalize being "Required" as soon as the user focuses on them.
- Use: `aria-required="true"`

**Non-thorough list of UIs where this is needed:**

- Login
- Registration
- Coupon field
- Payment details
- My Account > Personal details
- My Account > Password
- My Account > Email Address

**Screenshots**
**Example of potential solution**

Screen Shot 2021-09-09 at 7 59 38 PM 2

### PR DESCRIPTION
**Pull request by Pucek9**
Closes  #13678

### CODE REVIEW

**Comment by Pucek9** [comment]
ℹ Decided to use `required` instead of `aria-required`, see more: [When to use the required attribute vs the aria-required attribute for input elements?](https://stackoverflow.com/a/37975985/12372243)

ℹ `ng-select` doesn't use `required` or `aria-required` but it was possible to do it by  `[inputAttrs]="{ required: 'true' }"`
it doest have a sense for `span`/`label` elements 

❓  What about the cost center component? (feature-libs/checkout/components/components/cost-center/cost-center.component.html)
It uses standard `select` and I don't see the `required` attribute added, should it be or not?

**Review by Matejk00 — DISMISSED** [review]

**Review by steinsebastian — DISMISSED** [review]
Reviewed changes in configurator-attribute-input-field.component.html and 
configurator-attribute-numeric-input-field.component.html.
Approved.

**Review by ChristophHi — DISMISSED** [review]

**Comment by KateChuen** [comment]
I see that the "required" is still missing for: (see bottom for screenshots)
- when writing a product's review and the focus is on the review stars
- for B2B, on this page: http://localhost:4200/powertools-spa/en/USD/organization/units/abs/addresses/create, when the focus is on the CITY field.

Other remarks: 
- B2B: http://localhost:4200/powertools-spa/en/USD/organization/budgets/create
 Although for the Start and End date we have the "required" now. It also has some weird value, like 0% or -9%
budgetMth
budgetYear


Review Stars issue:
reviewStars

City issue:
UnitCity

**Comment by Pucek9** [comment]
parialy fixed:
- dates (NVDA only) <input type="date" required> for unknown reason most of SRs doesnt read it in this case, even it's proper configuration

can not fix without huge component refactor:
- stars - it's not an input directly

**Review by developpeurweb — APPROVED** [review]
**Screen Readers support for B2B is not in scope for 5.0.**
I tested B2C "required" fields and they all seem to work for JAWS/NVDA/VO. Except for "Rating" which will be addressed in a separate ticket.

**Review by KateChuen — APPROVED** [review]
Opened ticket for the remaining 2 issues that will be fixed later: 
review stars: https://github.com/SAP/spartacus/issues/15039
start and end date: https://github.com/SAP/spartacus/issues/15040

**Pull request merged**
