### PR TITLE
fix/gh 10843

### LINKED ISSUE #10843: Navigating with prev/next: no scroll to top
Product coffee machine
-> use prev/next buttons to navigate between groups
=> UI does not scroll to beginning of group when changing group

Should behave the same way as variant config UI

### PR DESCRIPTION
**Pull request by luklus**
close #10843

### CODE REVIEW

**Review by Uli-Tiger — APPROVED** [review]

**Review by Uli-Tiger — CHANGES_REQUESTED** [review]
i guess this change would break variant configuration.

**Comment by Uli-Tiger** [comment]
@luklus: I think
` this.configUtils.scrollToConfigurationElement('.VariantConfigurationTemplate, .CpqConfigHeader');`
should work for both cases

**Comment by luklus** [comment]
> i guess this change would break variant configuration.

why? Your proposal does not work. we cant use VariantConfigurationTemplate in scroll. I changed to CpqConfigContent

**Comment by Uli-Tiger** [comment]
> > i guess this change would break variant configuration.
> 
> why? Your proposal does not work. we cant use VariantConfigurationTemplate in scroll. I changed to CpqConfigContent

_component configurator-previous-next-buttons.component.ts_ is used in context of CPQ (what we currently implement) and CPS/Variant Configuration (which already exists). There are different page (templates) and enhance different style classes used. In case of CPS/Variant style class is 'VariantConfigurationTemplate' in case of CPQ it is 'CpqConfigContent'.
If i understand the underlying code of 'this.configUtils.scrollToConfigurationElement' correctly, it just expects an locator and scrolls to the first hit, so i assumed using a locator '.VariantConfigurationTemplate, .CpqConfigContent' would work in both cases - will check this.

**Comment by Uli-Tiger** [comment]
working fine - i committed the change

**Review by Uli-Tiger — APPROVED** [review]

**Pull request merged**
