### PR TITLE
fix: add landmark to Store Finder page (#13520)

### LINKED ISSUE #13520: Add region landmarks to Find a Store page
**Describe the bug**

- Screen Reader users must be able to navigate by landmarks, currently, there aren't many nor labelled, therefore relevant sections on the page should be identified with meaningful landmarks names.

**Tell us the version of Spartacus**
- Library version: 4.0.0.

**To Reproduce**
1. Open any Screen Reader (VO, NVDA, JAWS).
2. Bring up the Rotor or Element List Menu.
3. Choose Landmarks view.
4. See absence of relevant landmarks.

**Expected behavior**

- Use only predefined landmarks https://wiki.wdf.sap.corp/wiki/display/spar/Landmarks
- `<cx-store-finder-search role="search" aria-label="Store Finder">`

### PR DESCRIPTION
**Pull request by BenjaminEmiliani**
Closes #13520

### CODE REVIEW

**Review by developpeurweb — DISMISSED** [review]
Works well with VO, JAWS and NVDA.

**Review by developpeurweb — DISMISSED** [review]

**Comment by saad-mo** [comment]
Hi @developpeurweb I have a broader questions on this store finder search box. 

This PR adds an aria label on `cx-store-finder-search` to add it to the landmarks menu and it works great. 

however, the combination of this `aria-label` combined with the `placeholder` and `aria-label` on the search input leads to a confusing narration. I just wanted to check if this is good as is or we need to make some modification to improve the narration? 

Screen Shot 2021-10-25 at 9 22 49 AM

**Comment by BenjaminEmiliani** [comment]
> however, the combination of this `aria-label` combined with the `placeholder` and `aria-label` on the search input leads to a confusing narration. I just wanted to check if this is good as is or we need to make some modification to improve the narration?
> 

This was done in closing #13439 since the AMP testing tool detects missing label. Maybe the labels can be improved?

**Comment by developpeurweb** [comment]
> Hi @developpeurweb I have a broader questions on this store finder search box.
> 
> This PR adds an aria label on `cx-store-finder-search` to add it to the landmarks menu and it works great.
> 
> however, the combination of this `aria-label` combined with the `placeholder` and `aria-label` on the search input leads to a confusing narration. I just wanted to check if this is good as is or we need to make some modification to improve the narration?
> 
> Screen Shot 2021-10-25 at 9 22 49 AM

@saad-mo YES you're right, this needs narration improvement. Also, the button says "search, empty group" because it's not a button (don't remember if there is a ticker for that already). I'm realizing the Main Search and the Quick Order search also have just a "search" aria-label. I would suggest **creating an additional ticket to standardize interactions but differentiate narrations** for all 3 search boxes and bringing designers into this for their recommendations.

**Review by developpeurweb — APPROVED** [review]

**Pull request merged**
