### PR TITLE
fix: add missing role button attribute to the button links

### PR DESCRIPTION
**Pull request by uroslates**
Closed https://jira.tools.sap/browse/CXSPA-8806

### CODE REVIEW

**Review by Pio-Bar — DISMISSED** [review]

**Review by Zeyber — DISMISSED** [review]

**Comment by developpeurweb** [comment]
@uroslates as per requirement in the ticket, it must be possible to interact with converted elements with both `Spacebar` and `Enter` keys. 
Currently they can only be activated using `Enter` as regular links. Can you please make sure all converted elements can also be activated using `Spacebar`.
Please ping me if you have any questions.
Thanks!

**Comment by uroslates** [comment]
> @uroslates as per requirement in the ticket, it must be possible to interact with converted elements with both `Spacebar` and `Enter` keys. Currently they can only be activated using `Enter` as regular links. Can you please make sure all converted elements can also be activated using `Spacebar`. Please ping me if you have any questions. Thanks!

Hi @developpeurweb, thanks for the message. Maybe I'm missing something but I was able to interact with links by using both Enter/Space buttons in Win/JAWS.

**Comment by uroslates** [comment]
@Zeyber I have added new Directive here for addressing spacebar/enter keys as specified by Miguel, but if using [simple buttons ](https://sap-cx.slack.com/archives/C06D16JCVS6/p1732198241568029) instead of links is acceptable solution I can reiterate over this again. Please feel free to let me know what U think. Thanks!

**Review by Zeyber — DISMISSED** [review]

**Comment by developpeurweb** [comment]
@uroslates the changes work well. One last thing though, can you please include the order cancellation buttons rework (screenshot below) on your PR. This was on @petarmarkov9449 end, but an auditor suddenly closed his ticket, so let's leave that ticket closed and introduce the changes in your PR. Thanks!

link to btn 1
link to btn 2
link to btn 3

**Comment by uroslates** [comment]
co-author @petarmarkov9449

**Comment by uroslates** [comment]
> @uroslates the changes work well. One last thing though, can you please include the order cancellation buttons rework (screenshot below) on your PR. This was on @petarmarkov9449 end, but an auditor suddenly closed his ticket, so let's leave that ticket closed and introduce the changes in your PR. Thanks!

@developpeurweb We have together with @petarmarkov9449 incorporated all of his changes (from his PR) into this PR. Hopefully it'll be all OK now.. Cheers!

**Review by developpeurweb — APPROVED** [review]

**Pull request merged**
