### PR TITLE
fix(a11y): Prevent horizontal scroll on smaller screens

### PR DESCRIPTION
**Pull request by sdrozdsap**
https://jira.tools.sap/browse/CXSPA-8025

### CODE REVIEW

**Review by Zeyber — DISMISSED** [review]

**Comment by developpeurweb** [comment]
@sdrozdsap can you please make the following adjustments as per screenshots below:

1. Misalignment on cart page

fit small screen misalignment

2. For some reason although on Mac it looks fine, it seems the Windows emulation still has a scroll bar, can you please review this. Perhaps the Back-to-Top button could be the issue, since it seems to exceed the small screen area.

windows small screen

**Review by developpeurweb — CHANGES_REQUESTED** [review]
Please refer to posted screenshots for required changes.

**Comment by sdrozdsap** [comment]
@developpeurweb First issue:
> Misalignment on cart page

Is addressed , however I have some troubles with reproducing the second issue:
> For some reason although on Mac it looks fine, it seems the Windows emulation still has a scroll bar, can you please review this. Perhaps the Back-to-Top button could be the issue, since it seems to exceed the small screen area.

I've tried the virtual windows machine, as well as citrix remote desktop with Chrome and Edge and wasn't able to observe the horizontal scroll. Could you please describe your environment and the steps to reproduce this issue?

**Review by developpeurweb — DISMISSED** [review]

**Comment by developpeurweb** [comment]
Looks good now.
no misalignment no scrollbar

**Review by Zeyber — APPROVED** [review]

**Pull request merged**
