### PR TITLE
feat: epd-visualization integration library (#13933)

### PR DESCRIPTION
**Pull request by sam-garland**

### CODE REVIEW

**Comment by Platonn** [comment]
Hi @sam-garland 
Would you mind updating the PR with develop (and resolve conflict), please?

I'd like to compare if both PRs contain exactly the same changes:
(`release/4.2.x` -> `epic/epd-visualization-maintenance` vs. `develop` -> `epic/epd-visualization`)

**Comment by sam-garland** [comment]
@Platonn - I have merged from develop and resolved the conflict with the develop branch.

**Review by Platonn — DISMISSED** [review]
Great stuff!

**Comment by sam-garland** [comment]
Moved to `integration-libs/epd-visualization` branch as requested.

Opened new PR to replace this one: #14754

**Pull request closed without merging**
