### PR TITLE
chore: Cypress 10.3 upgrade

### PR DESCRIPTION
**Pull request by justinlee01**
- Upgrade all `storefrontapp-e2e-cypress` dependencies to their latest version

### CODE REVIEW

**Comment by giancorderoortiz** [comment]
Please do not upgrade CYPRESS version unless you can provide specific and detailed proof that new version doesn't cause delays in the pipeline. 
Please provide timing comparison for all core e2e tests.

Related tickets: https://jira.tools.sap/browse/CXSPA-445,  https://jira.tools.sap/browse/CXSPA-442, https://jira.tools.sap/browse/CXSPA-441

**Comment by justinlee01** [comment]
@giancorderoortiz I noticed there is no `cypress/e2e/cx_ccv2` folder. Should I delete the `cy:run:ci:ccv2` and `cy:run:ci:ccv2-b2b` commands?

**Comment by justinlee01** [comment]
Closing as 10.3 has performance issues.

**Comment by giancorderoortiz** [comment]
Reopening for troubleshooting purposes with Cypress team

**Comment by giancorderoortiz** [comment]
@justinlee01, please fix merge conflicts. Trying to troubleshoot perf issues with Cypress team.

**Pull request closed without merging**
