### PR TITLE
 feat: introduce new logging service (GH-2196)

### LINKED ISSUE #2196: Add logger service
We have a lot of places in code with console warnings.
It always need inject serverConfig for verify production flag like:

```ts
constructor(
    // ...
    private serverConfig: ServerConfig // or other config
  ) {}

// ...
if (!this.serverConfig.production) {
      console.warn(`content`);
    }
// ...
```
let's clean code little bit to get:
```ts
constructor(
    // ...
    private logger: Logger
  ) {}

// ...
this.logger.warn(`content`)
// ...
```

Please consider & discuss with @tobi-or-not-tobi possibility to use importable or even global service

### PR DESCRIPTION
**Pull request by WTPar**
this logging service will only log messages while not in production module

closes #2196

### CODE REVIEW

**Comment by WTPar** [comment]
Please be aware that this is a corporate contribution on behalf of Webtiser, which is still in the process of signing the corporate CLA

**Comment by WTPar** [comment]
The coorporate Contributors license agreement has just been signed

**Comment by marlass** [comment]
Hi,
server config has been removed (https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3362)

Could you update your PR?

**Comment by kacperknapik** [comment]
Waiting for changes @WTPar

**Comment by giancorderoortiz** [comment]
Closing due to many months of inactivity.
If still relevant, please update PR with latest develop branch, and re-open with meaningful comments so that it can be evaluated by development team.

**Pull request closed without merging**
