### PR TITLE
fix: header's click listner collapseMenuIfClickOutside should check event.currentTarget

### PR DESCRIPTION
**Pull request by alvteren**
header's click listher collapseMenuIfClickOutside should check event.currentTarget instead of event.target.
If you click by element inside header in event.target you have other element instead of <header>

if you click by svg your application crash with error
```
ERROR TypeError: event.target.className.includes is not a function
    at CustomStorefrontComponent.collapseMenuIfClickOutside (spartacus-storefront.js:18782)
    at CustomStorefrontComponent_Template_header_click_0_listener (custom-storefront.component.html:8)
    at executeListenerWithErrorHandling (core.js:21806)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:21855)
    at HTMLElement.<anonymous> (platform-browser.js:976)
```
Because className is not type of string for svg

### CODE REVIEW

**Comment by alvteren** [comment]
I debugged demo site
image
image
class "search fas fa-search" is not header

**Comment by tobi-or-not-tobi** [comment]
QA Steps: 
- add an embedded or inline SVG to the header element
- click on the svg and verify that you don't see the error


```svg
<svg height="100" width="100">
        <circle
          cx="50"
          cy="50"
          r="40"
          stroke="black"
          stroke-width="3"
          fill="red"
        />
</svg>
```

**Review by tobi-or-not-tobi — APPROVED** [review]

**Comment by alvteren** [comment]
> QA Steps:
> 
> * add an embedded or inline SVG to the header element
> * click on the svg and verify that you don't see the error

If You add SVG to `<cx-icon class="search fas fa-search"><cx-icon>` you can see it.

**Comment by tobi-or-not-tobi** [comment]
Pipeline blocked by #4386.

**Pull request merged**
