### PR TITLE
fix: add vocalized feedback to global messages

### LINKED ISSUE #13677: All global message notifications should be vocalized as soon as they happen
**Describe the bug**
- Consistently and all throughout, none of the global message notifications are currently being vocalized by any screen reader software.

**Tell us the version of Spartacus**
- Library version: 4.0.0

**To Reproduce**

1. Open any Screen Reader (VO, NVDA, JAWS).
2. Go to the Sign-In page
3. Introduce a valid email address and an invalid password.
4. See error alert on top, and hear the absence of vocalization of that alert.

**Expected behavior**
- All Global message notifications get vocalized as soon as they happen.
- As some notifications require immediate user attention and others don't, please assign as follows:
- MSG_TYPE_CONFIRMATION use `aria-live="polite" aria-atomic="true"`
- MSG_TYPE_INFO use `aria-live="polite" aria-atomic="true"`
- MSG_TYPE_WARNING use `aria-live="assertive" aria-atomic="true"`
- MSG_TYPE_ERROR use `aria-live="assertive" aria-atomic="true"`

**Screenshots**

Screen Shot 2021-09-09 at 8 39 49 PM

**Example of potential solution**

Screen Shot 2021-09-09 at 8 10 50 PM

### PR DESCRIPTION
**Pull request by BenjaminEmiliani**
Closes #13677

### CODE REVIEW

**Comment by saad-mo** [comment]
Code changes look good. Let's wait for @developpeurweb to his SR review.

**Review by developpeurweb — CHANGES_REQUESTED** [review]
This works well with VoiceOver.
Unfortunately, it doesn't work with JAWS and NVDA.
I don't have modification suggestions at this point. I'll keep researching, gather some references and get back to you.

**Review by hackergil — APPROVED** [review]

**Review by developpeurweb — APPROVED** [review]
Tested on VoiceOver, JAWS and NVDA. Works well on all three.

**Comment by saad-mo** [comment]
pls update PR title to include `fix:` prefix

**Pull request merged**
