### PR TITLE
chore: fix errors in order lib unit tests

### PR DESCRIPTION
**Pull request by rmch91**

### CODE REVIEW

**Comment by kimhw0630** [comment]
> nx run order:test

Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
✔ Browser application bundle generation complete.
31 10 2023 11:37:51.255:WARN [karma]: No captured browser, open http://localhost:9876/
31 10 2023 11:37:51.295:INFO [karma-server]: Karma v6.4.1 server started at http://localhost:9876/
31 10 2023 11:37:51.296:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
31 10 2023 11:37:51.302:INFO [launcher]: Starting browser Chrome
31 10 2023 11:37:54.025:INFO [Chrome 118.0.0.0 (Mac OS 10.15.7)]: Connected on socket sPROq36yFSpV5yTZAAAB with id 69083760
 Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 80 of 538 SUCCESS (0 secs / 0.49 secs)
 Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 160 of 538 SUCCESS (0 secs / 0.708 secs)
 WARN: 'cxDate pipe: No locale data registered for '' (see https://angular.io/api/common/registerLocaleData).'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 163 of 538 SUCCESS (0 secs / 0.713 secs)
WARN: 'cxDate pipe: No locale data registered for '' (see https://angular.io/api/common/registerLocaleData).'

WARN: 'cxDate pipe: No locale data registered for '' (see https://angular.io/api/common/registerLocaleData).'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 163 of 538 SUCCESS (0 secs / 0.713 secs)
WARN: 'cxDate pipe: No locale data registered for '' (see https://angular.io/api/common/registerLocaleData).'
 Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 243 of 538 SUCCESS (0 secs / 0.88 secs)
 Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 323 of 538 SUCCESS (0 secs / 0.996 secs)
 Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 403 of 538 SUCCESS (0 secs / 1.045 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 403 of 538 SUCCESS (0 secs / 1.045 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 403 of 538 SUCCESS (0 secs / 1.045 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'
 ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 405 of 538 SUCCESS (0 secs / 1.048 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'

 ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 407 of 538 SUCCESS (0 secs / 1.05 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'

ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 407 of 538 SUCCESS (0 secs / 1.05 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'
 ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 409 of 538 SUCCESS (0 secs / 1.053 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'

 ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 411 of 538 SUCCESS (0 secs / 1.056 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'

 ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 414 of 538 SUCCESS (0 secs / 1.061 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'

 ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 416 of 538 SUCCESS (0 secs / 1.063 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'

 ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 418 of 538 SUCCESS (0 secs / 1.065 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'

 ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 420 of 538 SUCCESS (0 secs / 1.067 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'

 ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'test-error'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 422 of 538 SUCCESS (0 secs / 1.069 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'test-error'

ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'test-error'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 422 of 538 SUCCESS (0 secs / 1.069 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'test-error'
 ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'test-error'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 424 of 538 SUCCESS (0 secs / 1.071 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'test-error'

ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'test-error'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 424 of 538 SUCCESS (0 secs / 1.071 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'test-error'
 ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'test-error'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 427 of 538 SUCCESS (0 secs / 1.076 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'test-error'

ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'test-error'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 427 of 538 SUCCESS (0 secs / 1.076 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'test-error'
 ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'test-error'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 429 of 538 SUCCESS (0 secs / 1.078 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'test-error'

ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'test-error'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 429 of 538 SUCCESS (0 secs / 1.078 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'test-error'
 ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 431 of 538 SUCCESS (0 secs / 1.081 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'

ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 431 of 538 SUCCESS (0 secs / 1.081 secs)
ERROR: 'Error passed to normalizeHttpError is not HttpErrorResponse instance', 'Error'
 Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 511 of 538 SUCCESS (0 secs / 1.155 secs)
 Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 538 of 538 SUCCESS (1.439 secs / 1.183 secs)
.
Chrome 118.0.0.0 (Mac OS 10.15.7): Executed 538 of 538 SUCCESS (1.439 secs / 1.183 secs)
TOTAL: 538 SUCCESS
TOTAL: 538 SUCCESS

**Review by kimhw0630 — APPROVED** [review]

**Comment by kimhw0630** [comment]
@rmch91  The error, 'Error passed to normalizeHttpError is not an instance of HttpErrorResponse,' can be resolved in most cases.
search for `const mockError = 'test-error' / 'Error' `and change to `const mockError = new HttpErrorResponse({ error: 'test-error' });`
some places you might need to use `normalizeHttpError(mockError)` 
e.g.
```
const completion = new OrderActions.CancelReplenishmentOrderFail(
        normalizeHttpError(mockError)
      );
```
also, 'cxDate pipe: No locale data registered for '' (see https://angular.io/api/common/registerLocaleData).' can also be resolved by including `MockDatePipe` in the declarations within the my-account-v2-consignment-entries.component.spec.ts

**Review by kimhw0630 — CHANGES_REQUESTED** [review]
The error, 'Error passed to normalizeHttpError is not an instance of HttpErrorResponse,' can be resolved

Ah, it's 'isDevMode,' so it executes 'console.error(logMessage, error)' from the 'normalizeHttpErro' function.

**Review by kimhw0630 — DISMISSED** [review]

**Comment by rmch91** [comment]
@kimhw0630 i added spyOn(console, 'error').and.stub(); to get rid of this errors

**Review by kimhw0630 — DISMISSED** [review]

**Comment by rmch91** [comment]
@kimhw0630 but now i'm thinking that it is not a good idea to stub console.error. I'am afraid that it could "mute" potentially different errors, that will be real errors, and it will be hard to understand in the future the reason of errors...

**Review by kimhw0630 — APPROVED** [review]

**Pull request merged**
