### PR TITLE
fix: add screen reader attribute to page title (#13556)

### LINKED ISSUE #13556: When the user changes the page this doesn't trigger Screen Reader narration
**Describe the bug**

- When the user changes the page this doesn't trigger Screen Reader narration, detailing **where the user has landed** and elements on the new page.
- Basically, the focus stays trapped on the last read element of the previous page and there's silence as the user lands on a new page.
- Most Screen Readers start "read mode" on landing, this doesn't happen because the focus is trapped.

**Tell us the version of Spartacus**
- Library version: 4.0.0

**To Reproduce**
1. Open any Screen Reader (VO, NVDA, JAWS)
2. Tab to Film Cameras Menu option, press Enter to follow the link.
3. Notice how even if the user has changed to a new page (Category Listings) the focus remains on the navigation link.
4. In other cases, it seems the focus moves automatically to the <main> area, instead of having their <title> read on landing.

**Pages having this issue (non-exhaustive list):**

- Homepage
- Category Listings
- Product Details Page
- Order Confirmation
- Order History
- Order Details
- Cancel Items
- Cancel Order
- Cancel Order Confirmation
- My Account > All pages

**Expected behavior**
- When landing on a Spartacus page, the page title gets narrated by the Screen Reader.

**Screenshots**

### PR DESCRIPTION
**Pull request by BenjaminEmiliani**
Closes #13556

### CODE REVIEW

**Review by saad-mo — DISMISSED** [review]
The changes work to fix the narration issue. However, there is another issue with component caching. not exactly sure how to fix it but here is the description of the issue.

When navigating from a category search page to a landing page and then to another category search page, the bread crumb component has the text from the previous category search page and after a split second the text updates. It's a minor inconvenience for the sighted user, but for SR users, both text values get narrated which is confusing. 

Steps to reproduce: 
1. From the electronics home page click on `Film Cameras` in the top menu and observe "2 results for Film cameras" text and narration.
2. Click on `Homepage` in the top menu and observe "homepage" is narrated among other things 
3. Click on `Camcorders`  in the top menu and observe the initial text of "2 results for Film cameras" in the bread crumb heading and it gets updated to  "6 results for Hand-held Camcorders" after a split second. This also gets picked up by the Screen Reader and announces both the initial value and updated value.  

Maybe there is a way to clear component value when you navigate away from a pace so that the page load, the initial value is empty and the new value is populated.

**Comment by saad-mo** [comment]
adding `debounceTime` to delay the rending of the title definitely improved the SR narration. I would let @developpeurweb make the final call here.

**Review by dydome — DISMISSED** [review]
The problem still persist, may you take a look @BenjaminEmiliani

**Comment by BenjaminEmiliani** [comment]
> The problem still persist, may you take a look @BenjaminEmiliani

@dydome Are you sure you tested on latest push? Currently on this branch the issue is fixed but using debounceTime

**Comment by dydome** [comment]
https://user-images.githubusercontent.com/18736434/155111427-c9a205b8-463a-4f27-ad90-40f77c6830fb.mov

Yes, the problem still persists, please take a look.

**Review by dydome — APPROVED** [review]

**Pull request merged**
