### PR TITLE
fix: checkout pages headings structure optimization

### LINKED ISSUE #13372: Checkout Pages Headings structure needs optimization
**Describe the bug**
While using a Screen Reader and navigating page content using the Elements Dialog the headings' current structure doesn't provide a logical sequence, this is more noticeable on Screen Readers that will "nest" headings like NVDA (screenshots below).

**Tell us the version of Spartacus**
- Library version: 4.0.0

**To Reproduce**
1. Add products to cart
2. Start checkout process
3. Open NVDA on Windows
4. Open Elements List (Ins+f7) and select "Headings"
5. See errors, as per screenshots below.

**Expected behavior**

- Remove "Order Summary" and "Cart Total" from the headings structure, make them a `<div>` to make the nesting look more logical.
- Notice there are also some title inconsistencies (e.g. Delivery Mode/Shipping Method) that need feedback from designers.

**Screenshots**

1. Shipping Address Page
address nvda

2. Shipping Method
method nvda

3. Payment Method
payment nvda

4. Review Order
review nvda

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome Version 92.0.4515.107
- SR: NVDA 2021.1

### PR DESCRIPTION
**Pull request by saad-mo**
Closes #13372

### CODE REVIEW

**Review by developpeurweb — COMMENTED** [review]
Can we change the heading for a `<div>` for this one too? AMP Tool will flag it as an "inappropriate jump".


Screen Shot 2021-12-10 at 2 03 34 PM

**Comment by saad-mo** [comment]
> Can we change the heading for a `<div>` for this one too? AMP Tool will flag it as an "inappropriate jump".
> 
>  Screen Shot 2021-12-10 at 2 03 34 PM

@developpeurweb updated. pls check again.

**Comment by developpeurweb** [comment]
@saad-mo I accidentally resized the window and found this one below, it will show up on mobile SR.
Heading text really doesn't make sense in there. But for now, can you please set it up as an `<h2>` so the heading order is preserved in mobile.

**Comment by saad-mo** [comment]
> @saad-mo I accidentally resized the window and found this one below, it will show up on mobile SR. Heading text really doesn't make sense in there. But for now, can you please set it up as an `<h2>` so the heading order is preserved in mobile.
> 
I saw it in the code, but left it because I thought it made sense on mobile, but seems like it needs to be removed as well.

**Review by developpeurweb — APPROVED** [review]

**Pull request merged**
