### PR TITLE
fix: (CXSPA-1087) - Role presentation for cx-message wrapper

### PR DESCRIPTION
**Pull request by Pio-Bar**
Ticket: [CXSPA-1087](https://jira.tools.sap/browse/CXSPA-1087)

Adding presentation 'role' to the wrapping div should stop the additional step in VO.

### CODE REVIEW

**Review by Zeyber — DISMISSED** [review]

**Review by developpeurweb — CHANGES_REQUESTED** [review]
This fixes the repetition on VO, but now I can hear the repetition on JAWS, can you please check if it's the same for you? 
Is it possible to fix it for both?

**Comment by Pio-Bar** [comment]
> This fixes the repetition on VO, but now I can hear the repetition on JAWS, can you please check if it's the same for you? Is it possible to fix it for both?

I've added additional roles that should help. I'm unsure why JAWS in particular would target those specific elements.

**Review by Zeyber — APPROVED** [review]

**Review by Zeyber — DISMISSED** [review]

**Comment by developpeurweb** [comment]
@Pio-Bar still an issue on JAWS, it seems there are two alert roles, as per screenshot, let's remove the alert role at the bottom and just leave the text. If not possible, let's remove the whole arrangement at the bottom and keep only the top alert.
duplicated role alert

**Comment by Pio-Bar** [comment]
I have removed the additional form error at the bottom. Just to summarize: 

- The double stop for VO should no longer appear. 
- JAWS should not repeat the error message twice.

**Review by rmch91 — DISMISSED** [review]

**Review by developpeurweb — DISMISSED** [review]

**Review by Zeyber — APPROVED** [review]

**Pull request merged**
