### PR TITLE
CXSPA-1720: Specify the emulated user for /paymenttypes endpoint when in ASM mode

### PR DESCRIPTION
**Pull request by justinlee01**
- Using the sap-commerce-cloud-user-id header

### CODE REVIEW

**Review by plabadie — APPROVED** [review]

**Comment by ercultimate** [comment]
Does this have an effect?

**Comment by justinlee01** [comment]
@ercultimate It gets consumed by `UserIdHttpHeaderInterceptor` - see `feature-libs/asm/root/interceptors/user-id-http-header.interceptor.ts`.

**Comment by ercultimate** [comment]
> @ercultimate It gets consumed by `UserIdHttpHeaderInterceptor` - see `feature-libs/asm/root/interceptors/user-id-http-header.interceptor.ts`.

I understand that the request will now carry the user ID header.  I'm asking if the change fixes the ticket issue.  Last I tried testing this, there was no change in response.

**Comment by justinlee01** [comment]
@ercultimate Ah, my bad. If you are emulating a customer while on a B2B site and try to checkout - yes, this does solve the original issue, where "/paymenttypes" does not resolve and throws some error.

**Review by ercultimate — APPROVED** [review]

**Pull request merged**
