### PR TITLE
Export initializers as DI-Tokens

### PR DESCRIPTION
**Pull request by fgn-sybit**
We overloaded LanguageService and had our own initialize-method in 3.4.2
Now Upgrading to 4 you don't call langaugeService.initialize() anymore and suggest using the LanguageInitializer.
Nice Idea ... so please export it 🤷‍♂️😁

### CODE REVIEW

**Comment by i507132** [comment]
How is this going? We need this...

**Comment by fgn-sybit** [comment]
> How is this going? We need this...

Do you have any idea how to get a reviewer looking at this?

**Comment by i507132** [comment]
> > How is this going? We need this...
> 
> Do you have any idea how to get a reviewer looking at this?


Maybe we can tag them. @Platonn

**Comment by Platonn** [comment]
Hi @fgn-sybit Thanks for reporting it! 

I created a ticket for it https://github.com/SAP/spartacus/issues/15690, which should be fixed in the latest 4.x soon

In the meantime IMHO it’s justified to use the following workaround: https://github.com/SAP/spartacus/issues/15690#issuecomment-1113114614

PS. Sorry we missed your PR. Next time please create a GitHub ticket, as we don’t monitor new PRs, but rather new tickets ;)

--
Closing in favour of https://github.com/SAP/spartacus/pull/15691

**Pull request closed without merging**
